sudo: false
language: cpp
compiler:
  - clang
  - gcc
env:
  - CONFIG=debug EXTCALL=manual
  - CONFIG=release EXTCALL=manual
  - CONFIG=debug EXTCALL=dyncall
  - CONFIG=release EXTCALL=dyncall
script: 
  - if [[ !("$CXX" == "clang++" && "$TRAVIS_OS_NAME" == "linux") && "$CONFIG" == "debug" && "$EXTCALL" == "manual" ) ]]; then make test config=coverage extcall=manual; fi
  - make test config=$CONFIG extcall=$EXTCALL
after_success: bash codecov.sh
