sudo: false
language: cpp
compiler:
  - clang
  - gcc
env:
  matrix:
    - CONFIG=debug EXTCALL=manual
    - CONFIG=release EXTCALL=manual
    - CONFIG=sanitize EXTCALL=manual
    - CONFIG=debug EXTCALL=dyncall
    - CONFIG=release EXTCALL=dyncall
    - CONFIG=sanitize EXTCALL=dyncall
  global:
   - secure: "I1bxcJWCo0PVjvKqSh+XaYg9x0o2pptgRg6hS1rfLT6W+8rivxrCyUcaWmDNWFyFoQxH8iU5U2ToXYj1q3R7Y0qZG+TCdr5P4P7NCgEc96Q5711WPyTLzzO/Y4+wsi1JaCFr1MwHLZ1+2XFLK/A62zlSNf2yB9zRQgNDE3+hez/uY7IRZWHTPzQI69iE0dMfI6uWLGnDV8HM3yyCWcK56N4saoTvlW5fNipC3qcx0sfmZfVtT4xKIvWKtRfnU8pCWvI2EfewXzOQwKOU9+urXoFeOCVAe6ti/9wDuFBQvglekJ9xTNdTHXNnLkUHeQtkYLsGU+a4beXIcYp2U0xSu2FZ64IVOcH0oIeW5+e5ny5otiomBNrvaJM45QU59TP2ucrs7DImj4zaRgc4y4gFEuO7ZswdynqbXqtT7EjCF66czndeg5DdLWBZvaSi0u3KqRiljbyYWx9Qz2RxpLSJfmGxQLsbXSegGLPGOK8gRBqaTOVONeJWbk8RigECxLuKiVHVx9eAWFUhMiMbTq1wpdfA23LoTHUyRG2D0txXCO1qmxxyw9z+xYsxGLxmltjnbKty0hYMo8uAVQZy+/PvKfANj3AnbjD02MKUXOqYf/FFGme/hYVwEtniVEFzA3/IdMOHgaGlCpFf6TwhB5q1uaTpBO5GGQJb4AXQ5voEB5w="

script: 
  - if [[ ! ("$TRAVIS_COMPILER" == "clang") && ("$CONFIG" == "debug") && ("$EXTCALL" == "manual") ]]; then echo $TRAVIS_COMPILER; make test config=coverage extcall=manual; fi
  - make test config=$CONFIG extcall=$EXTCALL
after_success: bash codecov.sh

addons:
  coverity_scan:
    project:
      name: "WheretIB/nullc"
    notification_email: wheretib@gmail.com
    build_command_prepend: ""
    build_command: "make"
    branch_pattern: coverity_scan
