sudo: false
language: cpp
compiler:
  - clang
  - gcc
env:
  - CONFIG=debug
  - CONFIG=release
  - CONFIG=sanitize
script: 
  - if [[ ! ("$TRAVIS_COMPILER" == "clang") && ("$CONFIG" == "debug") ]]; then echo $TRAVIS_COMPILER; make test config=coverage; fi
  - make test config=$CONFIG
after_success: bash codecov.sh
